# Generated by Django 3.2.5 on 2021-07-24 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210724_0320'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='Paragraph',
        ),
        migrations.RenameField(
            model_name='paragraph',
            old_name='name',
            new_name='people',
        ),
    ]
