# Generated by Django 3.2.5 on 2021-07-24 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210724_0326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clearance',
            new_name='Customize',
        ),
    ]
