# Generated by Django 3.2.5 on 2021-07-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_clearance_customize'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=10000)),
                ('topic', models.CharField(max_length=10000)),
                ('image_url', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
