# Generated by Django 3.2.5 on 2021-07-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_background'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Background',
        ),
    ]
