# Generated by Django 3.2.5 on 2021-07-27 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
