# Generated by Django 3.2.5 on 2021-07-27 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_promo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewProduct',
        ),
    ]
