# Generated by Django 3.2.5 on 2021-07-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_payment_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customize1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('other', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Customize2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('other', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Customize3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('other', models.CharField(max_length=10000)),
            ],
        ),
    ]
